AWSTemplateFormatVersion: "2010-09-09"
Description: 'DDB Table for hospital appointment management'
Resources:
  HospitalAppointmentManagementTable:
    Type: AWS::DynamoDB::Table 
    Properties:
      AttributeDefinitions:
        - AttributeName: PK 
          AttributeType: S
        - AttributeName: SK 
          AttributeType: S
      KeySchema:
        - AttributeName: PK 
          KeyType: HASH 
        - AttributeName: SK 
          KeyType: RANGE 
      TableName: ShankaraHospitalTable
      BillingMode: PAY_PER_REQUEST 
      SSESpecification:
        SSEEnabled: true